// Code generated by xmocks; DO NOT EDIT.
package xmock

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"runtime"
)

type TestCaseXFS struct {
	Name        string
	Env         map[string]string
	Input       any
	Want        any
	WantErr     bool
	ErrContains string
	MockFn      func(m *MockXFS)
}

func NewMockXFS() *MockXFS {
	mock := &MockXFS{}
	mock.OnCall = &mockOnCallXFS{mock: mock}
	mock.SetReturn = &mockSetReturnXFS{mock: mock}
	return mock
}

type MockXFS struct {
	FilepathAbsFunc        func(path string) (string, error)
	RetrieveFullPathFunc   func(path string) (string, error)
	GetUserHomeDirFunc     func() (string, error)
	GetUserConfigDirFunc   func() (string, error)
	GetUserDataDirFunc     func() (string, error)
	GetUserCacheDirFunc    func() (string, error)
	GetUserStateDirFunc    func() (string, error)
	GetUserRuntimeDirFunc  func() (string, error)
	GetUserLogDirFunc      func() (string, error)
	ReadDirFunc            func(f *os.File, n int) ([]fs.DirEntry, error)
	IsDirFunc              func(path string) bool
	ExistsFunc             func(path string) bool
	OsStatFunc             func(name string) (os.FileInfo, error)
	OsOpenFunc             func(name string) (*os.File, error)
	OsOpenFileFunc         func(name string, flag int, perm os.FileMode) (*os.File, error)
	OsCreateTempFunc       func(dir, pattern string) (*os.File, error)
	OsRemoveFunc           func(name string) error
	OsRemoveAllFunc        func(path string) error
	OsChmodFunc            func(name string, mode os.FileMode) error
	OsMkdirFunc            func(name string, perm os.FileMode) error
	OsMkdirAllFunc         func(path string, perm os.FileMode) error
	GetVolumeFreeSpaceFunc func(currentPath string, requiredBytes uint64) (bool, error)
	GetRuntimeGOOSFunc     func() string
	IOCopyFunc             func(dst io.Writer, src io.Reader) (int64, error)
	OnCall                 *mockOnCallXFS
	SetReturn              *mockSetReturnXFS
}

func (m *MockXFS) panicIfNotConfigured() {
	pc, _, _, ok := runtime.Caller(2)
	methodName := "UnknownMethod"
	if ok {
		fullFnName := runtime.FuncForPC(pc).Name()
		shortName := fullFnName
		for i := len(fullFnName) - 1; i >= 0; i-- {
			if fullFnName[i] == '/' {
				shortName = fullFnName[i+1:]
				break
			}
		}
		methodName = shortName
	}
	panic(fmt.Sprintf("CRITICAL: Mock for %s not configured.", methodName))
}

func (oMock *MockXFS) FilepathAbs(path string) (string, error) {
	if oMock.FilepathAbsFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.FilepathAbsFunc(path)
}

func (oMock *MockXFS) RetrieveFullPath(path string) (string, error) {
	if oMock.RetrieveFullPathFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.RetrieveFullPathFunc(path)
}

func (oMock *MockXFS) GetUserHomeDir() (string, error) {
	if oMock.GetUserHomeDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetUserHomeDirFunc()
}

func (oMock *MockXFS) GetUserConfigDir() (string, error) {
	if oMock.GetUserConfigDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetUserConfigDirFunc()
}

func (oMock *MockXFS) GetUserDataDir() (string, error) {
	if oMock.GetUserDataDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetUserDataDirFunc()
}

func (oMock *MockXFS) GetUserCacheDir() (string, error) {
	if oMock.GetUserCacheDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetUserCacheDirFunc()
}

func (oMock *MockXFS) GetUserStateDir() (string, error) {
	if oMock.GetUserStateDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetUserStateDirFunc()
}

func (oMock *MockXFS) GetUserRuntimeDir() (string, error) {
	if oMock.GetUserRuntimeDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetUserRuntimeDirFunc()
}

func (oMock *MockXFS) GetUserLogDir() (string, error) {
	if oMock.GetUserLogDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetUserLogDirFunc()
}

func (oMock *MockXFS) ReadDir(f *os.File, n int) ([]fs.DirEntry, error) {
	if oMock.ReadDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadDirFunc(f, n)
}

func (oMock *MockXFS) IsDir(path string) bool {
	if oMock.IsDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.IsDirFunc(path)
}

func (oMock *MockXFS) Exists(path string) bool {
	if oMock.ExistsFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ExistsFunc(path)
}

func (oMock *MockXFS) OsStat(name string) (os.FileInfo, error) {
	if oMock.OsStatFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsStatFunc(name)
}

func (oMock *MockXFS) OsOpen(name string) (*os.File, error) {
	if oMock.OsOpenFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsOpenFunc(name)
}

func (oMock *MockXFS) OsOpenFile(name string, flag int, perm os.FileMode) (*os.File, error) {
	if oMock.OsOpenFileFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsOpenFileFunc(name, flag, perm)
}

func (oMock *MockXFS) OsCreateTemp(dir, pattern string) (*os.File, error) {
	if oMock.OsCreateTempFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsCreateTempFunc(dir, pattern)
}

func (oMock *MockXFS) OsRemove(name string) error {
	if oMock.OsRemoveFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsRemoveFunc(name)
}

func (oMock *MockXFS) OsRemoveAll(path string) error {
	if oMock.OsRemoveAllFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsRemoveAllFunc(path)
}

func (oMock *MockXFS) OsChmod(name string, mode os.FileMode) error {
	if oMock.OsChmodFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsChmodFunc(name, mode)
}

func (oMock *MockXFS) OsMkdir(name string, perm os.FileMode) error {
	if oMock.OsMkdirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsMkdirFunc(name, perm)
}

func (oMock *MockXFS) OsMkdirAll(path string, perm os.FileMode) error {
	if oMock.OsMkdirAllFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OsMkdirAllFunc(path, perm)
}

func (oMock *MockXFS) GetVolumeFreeSpace(currentPath string, requiredBytes uint64) (bool, error) {
	if oMock.GetVolumeFreeSpaceFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetVolumeFreeSpaceFunc(currentPath, requiredBytes)
}

func (oMock *MockXFS) GetRuntimeGOOS() string {
	if oMock.GetRuntimeGOOSFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetRuntimeGOOSFunc()
}

func (oMock *MockXFS) IOCopy(dst io.Writer, src io.Reader) (int64, error) {
	if oMock.IOCopyFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.IOCopyFunc(dst, src)
}

type mockOnCallXFS struct {
	mock *MockXFS
}

func (o *mockOnCallXFS) FilepathAbs(fn func(path string) (string, error)) {
	o.mock.FilepathAbsFunc = fn
}

func (o *mockOnCallXFS) RetrieveFullPath(fn func(path string) (string, error)) {
	o.mock.RetrieveFullPathFunc = fn
}

func (o *mockOnCallXFS) GetUserHomeDir(fn func() (string, error)) {
	o.mock.GetUserHomeDirFunc = fn
}

func (o *mockOnCallXFS) GetUserConfigDir(fn func() (string, error)) {
	o.mock.GetUserConfigDirFunc = fn
}

func (o *mockOnCallXFS) GetUserDataDir(fn func() (string, error)) {
	o.mock.GetUserDataDirFunc = fn
}

func (o *mockOnCallXFS) GetUserCacheDir(fn func() (string, error)) {
	o.mock.GetUserCacheDirFunc = fn
}

func (o *mockOnCallXFS) GetUserStateDir(fn func() (string, error)) {
	o.mock.GetUserStateDirFunc = fn
}

func (o *mockOnCallXFS) GetUserRuntimeDir(fn func() (string, error)) {
	o.mock.GetUserRuntimeDirFunc = fn
}

func (o *mockOnCallXFS) GetUserLogDir(fn func() (string, error)) {
	o.mock.GetUserLogDirFunc = fn
}

func (o *mockOnCallXFS) ReadDir(fn func(f *os.File, n int) ([]fs.DirEntry, error)) {
	o.mock.ReadDirFunc = fn
}

func (o *mockOnCallXFS) IsDir(fn func(path string) bool) {
	o.mock.IsDirFunc = fn
}

func (o *mockOnCallXFS) Exists(fn func(path string) bool) {
	o.mock.ExistsFunc = fn
}

func (o *mockOnCallXFS) OsStat(fn func(name string) (os.FileInfo, error)) {
	o.mock.OsStatFunc = fn
}

func (o *mockOnCallXFS) OsOpen(fn func(name string) (*os.File, error)) {
	o.mock.OsOpenFunc = fn
}

func (o *mockOnCallXFS) OsOpenFile(fn func(name string, flag int, perm os.FileMode) (*os.File, error)) {
	o.mock.OsOpenFileFunc = fn
}

func (o *mockOnCallXFS) OsCreateTemp(fn func(dir, pattern string) (*os.File, error)) {
	o.mock.OsCreateTempFunc = fn
}

func (o *mockOnCallXFS) OsRemove(fn func(name string) error) {
	o.mock.OsRemoveFunc = fn
}

func (o *mockOnCallXFS) OsRemoveAll(fn func(path string) error) {
	o.mock.OsRemoveAllFunc = fn
}

func (o *mockOnCallXFS) OsChmod(fn func(name string, mode os.FileMode) error) {
	o.mock.OsChmodFunc = fn
}

func (o *mockOnCallXFS) OsMkdir(fn func(name string, perm os.FileMode) error) {
	o.mock.OsMkdirFunc = fn
}

func (o *mockOnCallXFS) OsMkdirAll(fn func(path string, perm os.FileMode) error) {
	o.mock.OsMkdirAllFunc = fn
}

func (o *mockOnCallXFS) GetVolumeFreeSpace(fn func(currentPath string, requiredBytes uint64) (bool, error)) {
	o.mock.GetVolumeFreeSpaceFunc = fn
}

func (o *mockOnCallXFS) GetRuntimeGOOS(fn func() string) {
	o.mock.GetRuntimeGOOSFunc = fn
}

func (o *mockOnCallXFS) IOCopy(fn func(dst io.Writer, src io.Reader) (int64, error)) {
	o.mock.IOCopyFunc = fn
}

type mockSetReturnXFS struct {
	mock *MockXFS
}

func (r *mockSetReturnXFS) FilepathAbs(result0 string, err error) {
	r.mock.OnCall.FilepathAbs(func(path string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) RetrieveFullPath(result0 string, err error) {
	r.mock.OnCall.RetrieveFullPath(func(path string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserHomeDir(result0 string, err error) {
	r.mock.OnCall.GetUserHomeDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserConfigDir(result0 string, err error) {
	r.mock.OnCall.GetUserConfigDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserDataDir(result0 string, err error) {
	r.mock.OnCall.GetUserDataDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserCacheDir(result0 string, err error) {
	r.mock.OnCall.GetUserCacheDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserStateDir(result0 string, err error) {
	r.mock.OnCall.GetUserStateDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserRuntimeDir(result0 string, err error) {
	r.mock.OnCall.GetUserRuntimeDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserLogDir(result0 string, err error) {
	r.mock.OnCall.GetUserLogDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) ReadDir(result0 []fs.DirEntry, err error) {
	r.mock.OnCall.ReadDir(func(f *os.File, n int) ([]fs.DirEntry, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) IsDir(result bool) {
	r.mock.OnCall.IsDir(func(path string) bool {
		return result
	})
}

func (r *mockSetReturnXFS) Exists(result bool) {
	r.mock.OnCall.Exists(func(path string) bool {
		return result
	})
}

func (r *mockSetReturnXFS) OsStat(result0 os.FileInfo, err error) {
	r.mock.OnCall.OsStat(func(name string) (os.FileInfo, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) OsOpen(result0 *os.File, err error) {
	r.mock.OnCall.OsOpen(func(name string) (*os.File, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) OsOpenFile(result0 *os.File, err error) {
	r.mock.OnCall.OsOpenFile(func(name string, flag int, perm os.FileMode) (*os.File, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) OsCreateTemp(result0 *os.File, err error) {
	r.mock.OnCall.OsCreateTemp(func(dir, pattern string) (*os.File, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) OsRemove(err error) {
	r.mock.OnCall.OsRemove(func(name string) error {
		return err
	})
}

func (r *mockSetReturnXFS) OsRemoveAll(err error) {
	r.mock.OnCall.OsRemoveAll(func(path string) error {
		return err
	})
}

func (r *mockSetReturnXFS) OsChmod(err error) {
	r.mock.OnCall.OsChmod(func(name string, mode os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnXFS) OsMkdir(err error) {
	r.mock.OnCall.OsMkdir(func(name string, perm os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnXFS) OsMkdirAll(err error) {
	r.mock.OnCall.OsMkdirAll(func(path string, perm os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnXFS) GetVolumeFreeSpace(result0 bool, err error) {
	r.mock.OnCall.GetVolumeFreeSpace(func(currentPath string, requiredBytes uint64) (bool, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetRuntimeGOOS(result string) {
	r.mock.OnCall.GetRuntimeGOOS(func() string {
		return result
	})
}

func (r *mockSetReturnXFS) IOCopy(result0 int64, err error) {
	r.mock.OnCall.IOCopy(func(dst io.Writer, src io.Reader) (int64, error) {
		return result0, err
	})
}
